blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹â€â™‚ï¸ Ask a question
    url: https://discord.gg/CMDsBmhvyW
    about: Feel free to ask any questions on our Discord server.
  - name: ğŸ™‹â€â™‚ï¸ å’¨è¯¢é—®é¢˜
    url: https://discord.gg/CMDsBmhvyW
    about: å¦‚æœæ‚¨æœ‰ä»»ä½•é—®é¢˜ï¼Œè¯·éšæ—¶åœ¨æˆ‘ä»¬çš„ Discord æœåŠ¡å™¨ä¸Šè¯¢é—®ã€‚